name: Push-to-EC2

on:
  push:
    branches:
      - main
      - test1
      - test2

jobs:
  deploy:
    name: Deploy to EC2 on push to main/test1/test2 branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Extract branch name from the full reference string
            BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')

            # Go to Apache's root directory
            cd /var/www/html

            # Check which branch was pushed and deploy accordingly
            if [ "$BRANCH_NAME" = "main" ]; then
              TARGET_DIR="test1"
            elif [ "$BRANCH_NAME" = "test1" ]; then
              TARGET_DIR="test2"
            elif [ "$BRANCH_NAME" = "test2" ]; then
              TARGET_DIR="test3"
            else
              echo "No deployment action for branch: $BRANCH_NAME"
              exit 1
            fi

            # Check if the target directory exists
            if [ -d "$TARGET_DIR" ]; then
              # If the directory exists, pull the latest changes
              echo "Pulling latest changes for $TARGET_DIR"
              cd $TARGET_DIR
              sudo git pull origin $BRANCH_NAME
            else
              # If the directory doesn't exist, clone the repository
              echo "$TARGET_DIR does not exist. Cloning the repository."
              sudo git clone --branch $BRANCH_NAME https://github.com/prem7443/simple-php.git $TARGET_DIR
            fi
