name: Push-to-EC2

# Trigger deployment on push to main, test, or test2 branches
on:
  push:
    branches:
      - main
      - test
      - test2

jobs:
  deploy:
    name: Deploy to EC2 on push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure we're in the correct directory
            cd /var/www/html

            # Checkout the branch that triggered the workflow
            git checkout ${{ github.ref }}
            
            # Conditional logic for copying files to the corresponding folders
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              # Main branch => test1 folder
              sudo cp -r /var/www/html/* /var/www/html/test1/
            elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
              # Test branch => test2 folder
              sudo cp -r /var/www/html/* /var/www/html/test2/
            elif [[ "${{ github.ref }}" == "refs/heads/test2" ]]; then
              # Test2 branch => test3 folder
              sudo cp -r /var/www/html/* /var/www/html/test3/
            fi

            # Restart Apache to apply the changes
            sudo systemctl restart apache2
