name: Push-to-EC2

on:
  push:
    branches:
      - main
      - test
      - test2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set target folder based on branch
        id: vars
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [[ "$BRANCH" == "main" ]]; then
            echo "FOLDER=test1" >> "$GITHUB_OUTPUT"
          elif [[ "$BRANCH" == "test" ]]; then
            echo "FOLDER=test2" >> "$GITHUB_OUTPUT"
          elif [[ "$BRANCH" == "test2" ]]; then
            echo "FOLDER=test3" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload folder to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."  # Upload all repo content
          target: /home/ubuntu/${{ steps.vars.outputs.FOLDER }}

      - name: Move folder to Apache root and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/html/${{ steps.vars.outputs.FOLDER }}
            sudo mv /home/ubuntu/${{ steps.vars.outputs.FOLDER }} /var/www/html/${{ steps.vars.outputs.FOLDER }}
            sudo systemctl restart apache2
