name: Push-to-EC2

# Trigger deployment only on push to main branch, test, and test2 branches
on:
  push:
    branches:
      - main
      - test
      - test2

jobs:
  deploy:
    name: Deploy to EC2 on push to main, test, or test2 branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Conditional logic for copying files based on the branch
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              sudo cp -r /var/www/html/* /var/www/html/test1/
            elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
              sudo cp -r /var/www/html/* /var/www/html/test2/
            elif [[ "${{ github.ref }}" == "refs/heads/test2" ]]; then
              sudo cp -r /var/www/html/* /var/www/html/test3/
            fi

            # Move files from the home directory to /var/www/html (if necessary)
            sudo mv /home/* /var/www/html

            # Restart Apache to apply changes
       
