name: Push-to-EC2

on:
  push:
    branches:
      - main
      - test
      - test2

jobs:
  deploy:
    name: Deploy to EC2 on push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Debug: Print the current directory
        run: pwd

      - name: Debug: List files in /var/www/html
        run: ls /var/www/html

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure we're in the correct directory
            cd /var/www/html

            # Check the git status
            git status

            # Checkout the branch that triggered the workflow
            git checkout ${{ github.ref }}

            # List files in /var/www/html before moving
            ls /var/www/html

            # Conditional logic for copying files to the corresponding folders
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              sudo cp -r /var/www/html/* /var/www/html/test1/
            elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
              sudo cp -r /var/www/html/* /var/www/html/test2/
            elif [[ "${{ github.ref }}" == "refs/heads/test2" ]]; then
              sudo cp -r /var/www/html/* /var/www/html/test3/
            fi

            # List files in /var/www/html/test1, test2, and test3 after moving
            ls /var/www/html/test1/
            ls /var/www/html/test2/
            ls /var/www/html/test3/

            # Restart Apache to apply the changes
            sudo systemctl restart apache2
