name: Push-to-EC2

on:
  push:
    branches:
      - main
      - test1
      - test2

jobs:
  deploy:
    name: Deploy to EC2 on push to main/test1/test2 branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Go to Apache's root directory
            cd /var/www/html

            # Check which branch was pushed and deploy accordingly
            if [ "$GITHUB_REF_NAME" = "main" ]; then
              TARGET_DIR="test1"
              sudo rm -rf $TARGET_DIR
              sudo git clone https://github.com/prem7443/simple-php.git $TARGET_DIR
            elif [ "$GITHUB_REF_NAME" = "test1" ]; then
              TARGET_DIR="test2"
              sudo rm -rf $TARGET_DIR
              sudo git clone https://github.com/prem7443/simple-php.git $TARGET_DIR
            elif [ "$GITHUB_REF_NAME" = "test2" ]; then
              TARGET_DIR="test3"
              sudo rm -rf $TARGET_DIR
            else
              echo "No deployment action for branch: $GITHUB_REF_NAME"
            fi
