
name: Push-to-EC2

on:
  push:
    branches:
      - main
      - test
      - test2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Branch-specific file copy to EC2
      - name: Upload file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            ${{ github.ref == 'refs/heads/main' && 'test1' || '' }}
            ${{ github.ref == 'refs/heads/test' && 'test2' || '' }}
            ${{ github.ref == 'refs/heads/test2' && 'test3' || '' }}
          target: /home/ubuntu/

      - name: SSH and move to proper directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              sudo mv /home/ubuntu/test1 /var/www/html/test1
            elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
              sudo mv /home/ubuntu/test2 /var/www/html/test2
            elif [[ "${{ github.ref }}" == "refs/heads/test2" ]]; then
              sudo mv /home/ubuntu/test3 /var/www/html/test3
            fi
            sudo systemctl restart apache2
