name: Push-to-EC2

on:
  push:
    branches:
      - main
      - test1
      - test2

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set current branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: BRANCH
          script: |
            echo "Deploying branch: $BRANCH"

            # Install necessary software
            sudo apt-get -y update
            sudo apt-get install -y apache2 git

            sudo systemctl start apache2
            sudo systemctl enable apache2

            cd /var/www/html

            # Set deployment target folder based on branch
            if [ "$BRANCH" = "main" ]; then
              TARGET_DIR="test1"
            elif [ "$BRANCH" = "test1" ]; then
              TARGET_DIR="test2"
            elif [ "$BRANCH" = "test2" ]; then
              TARGET_DIR="test3"
            else
              echo "No deployment target defined for branch: $BRANCH"
              exit 0
            fi

            # Remove old deployment and fetch fresh
            sudo rm -rf "$TARGET_DIR"
            sudo git clone --branch "$BRANCH" https://github.com/prem7443/simple-php.git temp-repo
            sudo mkdir -p "$TARGET_DIR"
            sudo mv temp-repo/* temp-repo/.* "$TARGET_DIR"/ 2>/dev/null || true
            sudo rm -rf temp-repo

            echo "Deployment to $TARGET_DIR complete."
