
name: Push-to-EC2

on:
  push:
    branches:
      - main
      - test1
      - test2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH and deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Copy index.php into each test folder
            cp /home/ubuntu/index.php /home/ubuntu/test1/index.php
            cp /home/ubuntu/index.php /home/ubuntu/test2/index.php
            cp /home/ubuntu/index.php /home/ubuntu/test3/index.php

            # Move the correct test folder to Apache directory
            if [[ "${GITHUB_REF##*/}" == "main" ]]; then
              sudo mv /home/ubuntu/test1 /var/www/html/test1
            elif [[ "${GITHUB_REF##*/}" == "test1" ]]; then
              sudo mv /home/ubuntu/test2 /var/www/html/test2
            elif [[ "${GITHUB_REF##*/}" == "test2" ]]; then
              sudo mv /home/ubuntu/test3 /var/www/html/test3
            fi

            # Restart Apache
            sudo systemctl restart apache2
