name: Push-to-EC2

on:
  push:
    branches:
      - test1
      - test2

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy files via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Execute remote commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update and install required packages
            sudo apt-get -y update
            sudo apt-get install -y apache2 git

            # Start and enable Apache
            sudo systemctl start apache2
            sudo systemctl enable apache2

            # Go to Apache's root directory
            cd /var/www/html

            # Ensure test2 and test3 exist
            sudo mkdir -p test2 test3

            # Clean up and clone fresh code into test1
            sudo rm -rf test1
            sudo git clone https://github.com/prem7443/simple-php.git test1
