name: Push-to-EC2

on:
  push:
    branches:
      - main
      - test1
      - test2

jobs:
  deploy:
    name: Deploy to EC2 (Only Pull)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the workflow repo (local)
        uses: actions/checkout@v2

      - name: Set current branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: SSH into EC2 and pull latest changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: BRANCH
          script: |
            echo "Deploying branch: $BRANCH"
            cd /var/www/html

            # Map branch to target directory
            if [ "$BRANCH" = "main" ]; then
              TARGET_DIR="test1"
            elif [ "$BRANCH" = "test1" ]; then
              TARGET_DIR="test2"
            elif [ "$BRANCH" = "test2" ]; then
              TARGET_DIR="test3"
            else
              echo "No deployment target configured for branch: $BRANCH"
              exit 1
            fi

            echo "Target directory: $TARGET_DIR"

            # Pull only if target is a git repo
            if [ -d "$TARGET_DIR/.git" ]; then
              cd "$TARGET_DIR"
              echo "Pulling latest code into $TARGET_DIR..."
              sudo git reset --hard
              sudo git clean -fd
              sudo git pull origin "$BRANCH"
              echo "✅ Deployment to $TARGET_DIR completed."
            
           
              exit 1
            fi
