name: Push-to-EC2

on:
  push:
    branches:
      - main
      - test1
      - test2
      

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Capture the current branch name from GitHub Actions
            BRANCH_NAME="${{ github.ref_name }}"

            # Update the system and install required packages
            sudo apt-get -y update
            sudo apt-get install -y apache2 git

            # Start Apache service and ensure it runs on boot
            sudo systemctl start apache2
            sudo systemctl enable apache2

            # Navigate to Apache's web directory
            cd /var/www/html

            # Branch-specific deployment logic
            if [ "$BRANCH_NAME" = "main" ]; then
              # Remove the existing test1 folder and clone the repo for 'main' branch
              sudo rm -rf test1
              sudo git clone https://github.com/prem7443/simple-php.git test1
            elif [ "$BRANCH_NAME" = "test" ]; then
              # Remove the existing test2 folder and clone the repo for 'test' branch
              sudo rm -rf test2
              sudo git clone https://github.com/prem7443/simple-php.git test2
            else
              # If it's neither 'main' nor 'test', output a message
              echo "No deployment actions for branch: $BRANCH_NAME"
            fi
