name: Manual Test Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Dev
          - Alpha

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show selected environment
        run: echo "Deploying to environment:${{ github.event.inputs.environment }}"

